"""Part 4: Snacks(25) + Festival(15) + Beverages(10) = 50 recipes, SL_0341-SL_0390"""
import json
def m(i,n,c,d,p,ck,s,r,sp,ings,mt,t,cn):
    return {"id":f"SL_{i:04d}","names":{"english":n},"category":c,"difficulty":d,"prep_time_mins":p,"cook_time_mins":ck,"servings":s,"region":r,"spice_level":sp,"is_authentic":True,"ingredients":[{"name":x,"amount":y} for x,y in ings],"method":mt,"tips":t,"cultural_note":cn}
R=[]
# SNACKS (25) SL_0341-0365
R.append(m(341,"Chinese Rolls","snack","medium",30,15,12,"Island-wide",2,[("spring roll wrappers","12"),("chicken mince","300g"),("cabbage","1 cup shredded"),("carrot","1 grated"),("leeks","1"),("garlic","3 cloves"),("soy sauce","1 tbsp"),("egg","1 for sealing"),("breadcrumbs","1 cup"),("oil for frying","2 cups")],"1. Saute garlic, add mince, cook until done\n2. Add vegetables, soy sauce, cook 5 mins\n3. Cool the filling completely\n4. Place filling on wrapper, roll tightly\n5. Seal with egg wash, coat in breadcrumbs\n6. Deep fry until golden brown","Cool filling completely before wrapping to prevent soggy rolls.","Chinese rolls are Sri Lanka's most popular short eat, found in every bakery across the island."))
R.append(m(342,"Fish Cutlets","snack","medium",30,15,12,"Island-wide",2,[("canned fish","2 cans"),("potato","3 boiled"),("onion","1"),("green chili","3"),("curry leaves","1 sprig"),("chili powder","1 tsp"),("lime juice","1 tbsp"),("egg","2"),("breadcrumbs","1 cup"),("oil for frying","2 cups")],"1. Mash potatoes, flake fish\n2. Saute onions, chili, curry leaves\n3. Mix fish, potato, sauteed mixture, chili powder, lime\n4. Shape into patties\n5. Dip in beaten egg, coat with breadcrumbs\n6. Deep fry until golden","Shape cutlets uniformly for even cooking.","Fish cutlets are the quintessential Sri Lankan party snack, served at every celebration."))
R.append(m(343,"Mutton Rolls","snack","medium",40,15,12,"Island-wide",3,[("pancake wrappers","12"),("mutton mince","400g"),("onion","2"),("curry powder","2 tbsp"),("chili powder","1 tsp"),("potato","2"),("egg","2"),("breadcrumbs","1 cup"),("oil for frying","2 cups")],"1. Cook mutton mince with spices until dry\n2. Boil and mash potatoes, mix with mince\n3. Make thin pancakes from flour batter\n4. Place filling on pancake, roll into cylinder\n5. Coat in egg and breadcrumbs\n6. Deep fry until golden crispy","The filling must be completely dry to prevent bursting.","Mutton rolls are the premium version of the Sri Lankan roll, a bakery highlight."))
R.append(m(344,"Isso Wade (Prawn Fritters)","snack","medium",20,15,8,"Southern Province",2,[("urad dhal","1 cup"),("prawns","200g"),("onion","1"),("green chili","3"),("curry leaves","10"),("salt","to taste"),("oil for frying","2 cups")],"1. Soak urad dhal 4 hours, grind to thick paste\n2. Mix in chopped onion, chili, curry leaves\n3. Shape into flat rounds\n4. Place a whole prawn on top of each\n5. Deep fry until golden\n6. Drain and serve hot","Press the prawn firmly into the batter so it doesn't fall off.","Isso wade are the iconic prawn-topped fritters from Galle Face Green, Colombo's famous seaside promenade."))
R.append(m(345,"Patties (Meat Puffs)","snack","medium",40,25,12,"Island-wide",2,[("puff pastry","500g"),("chicken mince","300g"),("onion","1"),("potato","1"),("curry powder","1 tbsp"),("chili powder","1/2 tsp"),("egg","1 for wash"),("salt","to taste")],"1. Cook mince with spices, onion, diced potato\n2. Cool filling completely\n3. Roll out puff pastry, cut into circles\n4. Place filling, fold into half-moons\n5. Seal edges with fork, brush with egg wash\n6. Bake at 200C for 20-25 mins until puffed and golden","Chill pastry between steps for flakier results.","Patties are a colonial-era introduction that became a beloved Sri Lankan bakery staple."))
R.append(m(346,"Ulundu Vadai","snack","medium",20,15,8,"Northern Province",2,[("black gram (urad dhal)","1 cup"),("onion","1"),("green chili","3"),("ginger","1/2 inch"),("curry leaves","10"),("pepper","1/2 tsp"),("salt","to taste"),("oil for frying","2 cups")],"1. Soak dhal 4 hours, drain\n2. Grind to thick, fluffy paste without water\n3. Add chopped onion, chili, ginger, curry leaves, pepper\n4. Shape into donut shape with hole in center\n5. Deep fry in medium-hot oil\n6. Fry until deep golden brown on both sides","The paste must be thick - add no water while grinding.","Ulundu vadai is a classic Jaffna Tamil snack, traditionally offered at Hindu temples."))
R.append(m(347,"Egg Rolls","snack","medium",25,15,8,"Island-wide",2,[("eggs","6 hard-boiled"),("chicken mince","200g"),("onion","1"),("curry powder","1 tbsp"),("pancake wrappers","6"),("egg beaten","1"),("breadcrumbs","1 cup"),("oil for frying","2 cups")],"1. Cook mince filling with spices\n2. Peel hard-boiled eggs\n3. Wrap each egg with mince filling\n4. Wrap in pancake wrapper\n5. Coat in beaten egg and breadcrumbs\n6. Deep fry until golden","Let the coated eggs chill 15 mins before frying for better adhesion.","Egg rolls are a popular party snack that combines the beloved Sri Lankan roll with a surprise egg center."))
R.append(m(348,"Vegetable Roti","snack","easy",15,15,6,"Island-wide",1,[("wheat flour","2 cups"),("grated coconut","1/2 cup"),("carrot","1 grated"),("leeks","1/2"),("green chili","2"),("onion","1"),("salt","1 tsp"),("water","as needed")],"1. Mix flour, coconut, salt\n2. Add finely chopped vegetables\n3. Add water to make stiff dough\n4. Shape into thick rounds\n5. Cook on hot griddle without oil\n6. Cook both sides till done","Chop vegetables very fine so they cook through.","Vegetable roti is a nutritious quick snack perfect for tea time."))
R.append(m(349,"Samosa","snack","medium",30,15,12,"Eastern Province",2,[("flour","2 cups"),("potato","3"),("onion","1"),("green peas","1/2 cup"),("cumin seeds","1 tsp"),("chili powder","1 tsp"),("garam masala","1/2 tsp"),("oil for frying","2 cups"),("salt","to taste")],"1. Make pastry dough with flour, oil, water\n2. Boil and mash potatoes roughly\n3. Saute onions, cumin, add potato, peas, spices\n4. Roll dough into circles, cut in half\n5. Form cone shape, fill with potato mixture, seal\n6. Deep fry until golden and crispy","Seal edges with water paste to prevent opening during frying.","Samosas in Sri Lanka are influenced by both Indian and Malay culinary traditions."))
R.append(m(350,"Achcharu Sticks (Pickle Sticks)","snack","easy",15,0,6,"Island-wide",3,[("green mango","1"),("guava","2"),("pineapple","1 cup"),("chili powder","1 tbsp"),("salt","1 tsp"),("sugar","1 tsp"),("vinegar","2 tbsp")],"1. Cut all fruits into stick shapes\n2. Thread onto wooden skewers\n3. Mix chili powder, salt, sugar, vinegar into paste\n4. Brush or dip fruit sticks into spice paste\n5. Arrange on plate\n6. Serve immediately","Use firm, unripe fruits for best crunch.","Achcharu sticks are the favorite after-school snack sold by vendors outside every school in Sri Lanka."))
R.append(m(351,"Kimbula Banis (Crocodile Bread)","snack","medium",60,25,8,"Island-wide",0,[("flour","3 cups"),("sugar","1/4 cup"),("yeast","1.5 tsp"),("warm milk","1 cup"),("butter","2 tbsp"),("egg","1"),("salt","1/2 tsp")],"1. Dissolve yeast in warm milk with sugar\n2. Mix flour, salt, add yeast mixture and egg\n3. Knead in butter until smooth dough\n4. Prove 1 hour until doubled\n5. Shape into crocodile form (elongated with pointed ends)\n6. Prove again 20 mins, bake at 180C for 20-25 mins","The classic shape has a bulge in the middle tapering at both ends.","Kimbula banis (crocodile buns) are a uniquely Sri Lankan bread shape, a beloved bakery item since colonial times."))
R.append(m(352,"Roast Paan (Bread)","snack","medium",90,30,8,"Island-wide",0,[("flour","4 cups"),("yeast","2 tsp"),("sugar","1 tbsp"),("salt","1 tsp"),("warm water","1.5 cups"),("oil","2 tbsp")],"1. Dissolve yeast in warm water with sugar\n2. Mix flour and salt\n3. Add yeast mixture and oil, knead 10 mins\n4. Prove 1 hour until doubled\n5. Shape into loaf, place in greased tin\n6. Prove 30 mins, bake at 200C for 25-30 mins","Knead thoroughly for proper gluten development.","Roast paan is Sri Lanka's signature bread, baked in wood-fired ovens in local bakeries every morning."))
R.append(m(353,"Manioc Chips","snack","easy",10,15,4,"Island-wide",1,[("manioc (cassava)","500g"),("turmeric","1/4 tsp"),("chili powder","1/2 tsp"),("salt","to taste"),("oil for frying","2 cups")],"1. Peel manioc, slice into thin chips\n2. Soak in salted turmeric water 10 mins\n3. Drain and pat dry thoroughly\n4. Deep fry in batches until golden and crispy\n5. Drain on paper\n6. Season with chili powder and salt while hot","Slice uniformly thin for even crisping. Dry well before frying.","Manioc chips are a popular tea-time snack and a crunchy accompaniment to drinks."))
R.append(m(354,"Banana Chips","snack","easy",10,15,4,"Island-wide",0,[("raw banana (ash plantain)","3"),("salt","1 tsp"),("turmeric","1/4 tsp"),("oil for frying","2 cups")],"1. Peel raw bananas\n2. Slice thinly using a mandoline\n3. Soak in salted turmeric water\n4. Drain and dry completely\n5. Deep fry until crispy and light golden\n6. Drain, cool, store in airtight container","Use a mandoline slicer for uniformly thin chips.","Banana chips are Sri Lanka's favorite crispy snack, perfect with evening tea."))
R.append(m(355,"Chickpea Salad (Kadala)","snack","easy",10,20,4,"Island-wide",2,[("dried chickpeas","2 cups"),("onion","1"),("green chili","3"),("grated coconut","3 tbsp"),("chili powder","1 tsp"),("lime juice","2 tbsp"),("salt","to taste")],"1. Soak chickpeas overnight, boil until tender\n2. Drain well\n3. Finely chop onion and green chili\n4. Mix chickpeas with onion, chili, coconut\n5. Season with chili powder, lime juice, salt\n6. Toss well and serve","Boil chickpeas with a pinch of baking soda for softer texture.","Kadala salad is the popular street-food snack sold at cricket matches and bus stands across Sri Lanka."))
R.append(m(356,"Mas Paan (Meat Bun)","snack","medium",45,20,8,"Island-wide",2,[("bread dough","500g"),("fish or chicken filling","2 cups"),("onion","1"),("chili powder","1 tsp"),("curry leaves","1 sprig"),("hard-boiled egg","4 halved"),("oil","1 tbsp")],"1. Prepare spiced meat or fish filling, cool\n2. Divide bread dough into 8 portions\n3. Flatten each, place filling in center with egg half\n4. Seal edges, shape into bun\n5. Prove 20 mins\n6. Bake at 190C for 18-20 mins until golden","Seal edges tightly to prevent filling from leaking.","Mas paan is the beloved Sri Lankan stuffed bun, an afternoon snack institution."))
R.append(m(357,"Konda Kavum (Hair Kavum)","snack","hard",20,30,10,"Island-wide",0,[("rice flour","2 cups"),("treacle","1 cup"),("coconut milk","1/2 cup"),("baking soda","1/4 tsp"),("oil for frying","3 cups")],"1. Mix treacle with coconut milk\n2. Add rice flour and baking soda to form thick batter\n3. Rest 20 minutes\n4. Heat oil to medium temperature\n5. Pour batter slowly, the hair-like strands form as it flows\n6. Fry until dark golden","The batter must flow in thin strands to create the signature 'hair' appearance.","Konda kavum get their name from the hair-like strands that form during frying, a traditional New Year sweet."))
R.append(m(358,"Lavariya Petti","snack","easy",15,20,6,"Southern Province",1,[("rice flour","2 cups"),("grated coconut","1 cup"),("onion","1"),("Maldive fish","1 tbsp"),("chili flakes","1 tsp"),("salt","to taste"),("banana leaf","for wrapping")],"1. Mix flour, coconut, onion, Maldive fish, chili, salt\n2. Add water to make thick dough\n3. Place portions on banana leaf squares\n4. Wrap into parcels\n5. Steam 15-20 minutes\n6. Serve in leaf wrapping","Soften banana leaves over flame before wrapping.","Lavariya petti are traditional steamed rice parcels from Southern Sri Lanka."))
R.append(m(359,"Isso Vadai (Jaffna Style)","snack","medium",20,15,8,"Northern Province",2,[("chana dhal","1 cup"),("onion","1"),("green chili","3"),("fennel seeds","1/2 tsp"),("curry leaves","10"),("prawns","16 small"),("salt","to taste"),("oil for frying","2 cups")],"1. Soak chana dhal 3 hours, grind coarsely\n2. Mix in chopped onion, chili, fennel, curry leaves\n3. Shape into flat rounds\n4. Press a small prawn on top of each\n5. Deep fry until crispy golden\n6. Drain and serve hot with chutney","Grind dhal coarsely for crunchy texture.","Jaffna-style isso vadai uses chana dhal instead of urad dhal, giving a crunchier texture."))
R.append(m(360,"Dhal Wade","snack","easy",15,15,8,"Island-wide",2,[("chana dhal","1 cup"),("onion","1"),("green chili","3"),("curry leaves","10"),("pepper","1/2 tsp"),("oil for frying","2 cups"),("salt","to taste")],"1. Soak chana dhal 3 hours\n2. Grind very coarsely (chunky)\n3. Mix with chopped onion, chili, curry leaves, pepper\n4. Shape into flat rounds\n5. Deep fry until crispy golden\n6. Drain and serve","Keep the grind very coarse for maximum crunch.","Dhal wade is a crunchy lentil fritter enjoyed across Sri Lanka as a snack."))
R.append(m(361,"Spring Rolls","snack","medium",25,15,10,"Island-wide",1,[("spring roll wrappers","10"),("cabbage","2 cups shredded"),("carrot","1"),("bean sprouts","1 cup"),("onion","1"),("garlic","3 cloves"),("soy sauce","1 tbsp"),("oil for frying","2 cups")],"1. Stir-fry vegetables with garlic and soy sauce\n2. Drain excess liquid, cool completely\n3. Place filling on wrapper corner\n4. Roll tightly, folding in sides\n5. Seal with flour paste\n6. Deep fry until crispy golden","Drain vegetables well - wet filling makes soggy rolls.","Spring rolls are a beloved snack at Sri Lankan Chinese restaurants."))
R.append(m(362,"Vegetable Cutlets","snack","easy",25,15,10,"Island-wide",1,[("potato","3"),("carrot","1"),("green peas","1/2 cup"),("beans","1/2 cup"),("onion","1"),("green chili","2"),("curry leaves","1 sprig"),("egg","2"),("breadcrumbs","1 cup"),("oil for frying","2 cups")],"1. Boil and mash potatoes\n2. Finely dice and cook carrots, peas, beans\n3. Saute onion, chili, curry leaves\n4. Mix everything with mashed potato\n5. Shape, dip in egg, coat breadcrumbs\n6. Deep fry until golden","Ensure vegetables are cooked but firm, not mushy.","Vegetable cutlets are the vegetarian option at every Sri Lankan bakery and party."))
R.append(m(363,"Prawn Crackers","snack","easy",5,5,4,"Island-wide",0,[("prawn crackers (uncooked)","200g"),("oil for frying","2 cups")],"1. Heat oil to very hot (180C)\n2. Drop a few crackers at a time\n3. They will puff up instantly in 3-5 seconds\n4. Turn once if needed\n5. Remove immediately when puffed\n6. Drain on paper and serve","Oil must be very hot - crackers should puff instantly.","Prawn crackers are a popular appetizer served at Sri Lankan Chinese restaurants."))
R.append(m(364,"Pol Petti (Coconut Pastry)","snack","medium",25,15,10,"Western Province",0,[("flour","2 cups"),("butter","100g"),("coconut","1 cup"),("jaggery","1/2 cup"),("cardamom","1/4 tsp"),("salt","pinch"),("water","as needed"),("oil for frying","2 cups")],"1. Make pastry: rub butter into flour, add water for dough\n2. Mix coconut, jaggery, cardamom for filling\n3. Roll pastry thin, cut into circles\n4. Place filling, fold into half-moons\n5. Seal edges with fork\n6. Deep fry until golden","Seal edges well to keep filling inside.","Pol petti are traditional coconut-filled pastries, a beloved sweet snack."))
R.append(m(365,"Tapioca Chips","snack","easy",10,15,4,"Island-wide",1,[("tapioca","500g"),("turmeric","1/4 tsp"),("chili powder","1/2 tsp"),("salt","to taste"),("oil for frying","2 cups")],"1. Peel tapioca, slice paper-thin\n2. Wash and soak in turmeric water\n3. Drain and dry completely\n4. Deep fry in batches until crispy\n5. Season with salt and chili powder\n6. Cool and store airtight","Slice extremely thin for maximum crispness.","Tapioca chips are a crunchy snack common in Southern and Sabaragamuwa provinces."))

# FESTIVAL (15) SL_0366-0380
R.append(m(366,"Sinhala New Year Kavum","festival","hard",30,45,15,"Island-wide",0,[("rice flour","3 cups"),("coconut milk","1 cup"),("kithul treacle","1.5 cups"),("salt","pinch"),("oil for deep frying","6 cups")],"1. Warm treacle slightly, mix with coconut milk\n2. Add rice flour gradually to make thick batter\n3. Rest batter 1 hour\n4. Heat oil to medium (not too hot)\n5. Pour small amounts using coconut shell ladle\n6. Fry very slowly, turning, until deep golden brown","Low and slow frying is the secret - rush it and outside burns.","Kavum is THE iconic Sinhala and Tamil New Year sweet, made on April 13th every year. The first kavum is ceremonially fried at the auspicious time."))
R.append(m(367,"Kokis (New Year Rosettes)","festival","hard",20,30,15,"Island-wide",0,[("rice flour","2 cups"),("coconut milk","1 cup"),("eggs","2"),("sugar","2 tbsp"),("turmeric","1/4 tsp"),("salt","pinch"),("oil for frying","4 cups")],"1. Mix all ingredients to smooth batter like thick cream\n2. Heat oil, heat kokis mold in oil\n3. Dip hot mold in batter to 3/4 depth only\n4. Immerse in oil, hold until kokis releases\n5. Fry until golden and crispy\n6. Drain and cool completely","If mold goes fully in batter, the kokis won't release from the mold.","Kokis are the crispy, flower-shaped cookies essential to the New Year table. Different families have different ancestral mold designs."))
R.append(m(368,"Kiribath for New Year","festival","easy",10,25,8,"Island-wide",0,[("short grain rice","3 cups"),("thick coconut milk","4 cups"),("salt","1.5 tsp")],"1. Wash rice and cook with water until half done\n2. Add thick coconut milk generously\n3. Cook on low heat, stirring gently\n4. Press into tray, smooth with wet spoon\n5. Cut into diamond shapes\n6. Serve at the auspicious New Year time with lunu miris","Make extra milk rice - it is the first food of the New Year.","Kiribath is ceremonially cooked at the exact auspicious time on Sinhala New Year morning, symbolizing prosperity for the coming year."))
R.append(m(369,"Athirasa (Sweet Rice Cakes)","festival","hard",30,30,12,"Island-wide",0,[("roasted rice flour","2 cups"),("jaggery","1 cup"),("sesame seeds","2 tbsp"),("water","as needed"),("oil for frying","3 cups")],"1. Grate jaggery, dissolve in minimal water\n2. Strain and cook until thick syrup\n3. Mix with rice flour to form stiff dough\n4. Rest overnight for better flavor\n5. Shape into flat rounds, press sesame seeds on top\n6. Deep fry on low heat until dark golden","Overnight resting makes the perfect texture.","Athirasa is an ancient festival sweet, predating even kavum in Sri Lankan culinary history."))
R.append(m(370,"Vesak Lantern Treats (Vesak Batti Mala)","festival","easy",15,15,10,"Island-wide",0,[("flour","2 cups"),("sugar","1/2 cup"),("coconut milk","1/2 cup"),("cardamom","1/4 tsp"),("cashews","2 tbsp"),("food coloring","assorted"),("oil for frying","2 cups")],"1. Mix flour, sugar, coconut milk, cardamom\n2. Divide dough into portions, color each differently\n3. Shape into small balls and crescents\n4. Deep fry until golden\n5. Drain well\n6. Arrange colorfully on plate like lantern shapes","Use natural food coloring for healthy treats.","These colorful sweets are made during Vesak festival to share with communities celebrating at temples."))
R.append(m(371,"Eid Biriyani","festival","hard",45,60,8,"Eastern Province",3,[("basmati rice","3 cups"),("lamb","750g"),("onion","4"),("yogurt","1 cup"),("biriyani masala","3 tbsp"),("saffron","1/2 tsp"),("ghee","4 tbsp"),("mint","1 cup"),("coriander","1 cup"),("rose water","1 tbsp"),("garlic","10 cloves"),("ginger","2 inch"),("whole spices","2 tbsp")],"1. Marinate lamb overnight in yogurt and spices\n2. Cook lamb until tender in its marinade\n3. Parboil rice with whole spices\n4. Deep fry onions until dark brown\n5. Layer: lamb, rice, fried onions, herbs, saffron milk\n6. Seal pot, dum cook 30 minutes on lowest heat","Overnight marination is non-negotiable for Eid biriyani.","Eid biriyani is the centerpiece of Sri Lankan Muslim celebrations, prepared in massive quantities to feed families and neighbors."))
R.append(m(372,"Pongal (Tamil Harvest Festival Rice)","festival","easy",10,30,6,"Northern Province",0,[("raw rice","1 cup"),("moong dhal","1/4 cup"),("jaggery","1 cup"),("coconut milk","1 cup"),("cardamom","3 pods"),("cashews","2 tbsp"),("raisins","2 tbsp"),("ghee","2 tbsp")],"1. Dry roast moong dhal until golden\n2. Cook rice and dhal together until soft\n3. Melt jaggery in water, strain\n4. Add jaggery syrup to cooked rice\n5. Add coconut milk, cardamom, cook 10 mins\n6. Temper cashews and raisins in ghee, garnish","Use freshly harvested rice for authentic Thai Pongal.","Thai Pongal celebrates the Tamil harvest festival in January. The rice is ceremonially boiled and allowed to overflow the pot, symbolizing abundance."))
R.append(m(373,"Christmas Cake","festival","hard",60,180,20,"Western Province",0,[("dried fruits","1 kg soaked in brandy"),("butter","500g"),("sugar","500g"),("eggs","12"),("flour","500g"),("treacle","2 tbsp"),("almond essence","1 tsp"),("vanilla","1 tsp"),("mixed spice","2 tsp"),("semolina","2 tbsp"),("honey","2 tbsp"),("cashews","200g"),("chow chow preserve","100g")],"1. Soak dried fruits in brandy for 2 weeks\n2. Cream butter and sugar until very light\n3. Add eggs one at a time, then treacle\n4. Fold in flour, semolina, spices\n5. Add soaked fruits, nuts, preserves\n6. Bake at 150C for 2.5-3 hours, test with skewer","Soak fruits at least 2 weeks ahead. Longer is better.","Sri Lankan Christmas cake is the richest, densest fruit cake in the Asian tradition, a pride of Burgher families."))
R.append(m(374,"Ramzan Special Falooda","festival","easy",15,10,4,"Eastern Province",0,[("falooda seeds","2 tbsp"),("falooda noodles","1/2 cup"),("milk","2 cups"),("rose syrup","3 tbsp"),("sugar","2 tbsp"),("ice cream","2 scoops"),("jelly","1/2 cup"),("pistachio","1 tbsp"),("almonds","1 tbsp")],"1. Soak falooda seeds until swollen\n2. Cook falooda noodles, cool\n3. Prepare rose milk with sugar\n4. Layer in tall glass: noodles, seeds, jelly cubes\n5. Pour cold rose milk\n6. Top with ice cream, crushed nuts","Assemble just before serving for best presentation.","Special falooda is prepared to break the Ramadan fast, a celebratory drink-dessert."))
R.append(m(375,"Deepavali Sweets Platter","festival","medium",30,20,12,"Northern Province",0,[("chickpea flour","1 cup"),("rice flour","1 cup"),("sugar","1 cup"),("milk","1/2 cup"),("ghee","for frying"),("cardamom","1/2 tsp"),("cashews","1/4 cup"),("sesame seeds","2 tbsp")],"1. Make ladoo: roast chickpea flour in ghee, add sugar syrup, shape\n2. Make murukku: mix rice flour with water, press through murukku maker into hot oil\n3. Make sweet seedai: mix rice flour with jaggery, shape into balls, fry\n4. Arrange all sweets on large platter\n5. Garnish with cashews and sesame\n6. Distribute to neighbors and friends","Each sweet type should be prepared separately.","Deepavali celebrates the victory of light over darkness. Tamil families in Sri Lanka prepare elaborate sweet platters."))
R.append(m(376,"Unduwap Poya Sweet Rice","festival","easy",15,30,6,"Island-wide",0,[("rice","2 cups"),("coconut milk","2 cups"),("jaggery","1/2 cup"),("cardamom","3 pods"),("pandan leaves","2"),("cashews","2 tbsp"),("raisins","2 tbsp")],"1. Cook rice in coconut milk with pandan leaves\n2. Melt jaggery in a little water, strain\n3. Mix jaggery into cooked rice\n4. Add cardamom\n5. Garnish with fried cashews and raisins\n6. Offer at temple and distribute","Use kithul jaggery for authentic temple offering flavor.","Sweet rice offerings are made at Buddhist temples during every Poya (full moon) day."))
R.append(m(377,"Thai Pongal with Sugarcane","festival","easy",15,30,6,"Northern Province",0,[("raw rice","2 cups"),("moong dhal","1/2 cup"),("milk","2 cups"),("jaggery","1 cup"),("cardamom","4 pods"),("ghee","3 tbsp"),("cashews","3 tbsp"),("sugarcane pieces","for decoration")],"1. Wash rice and dhal, cook together in pot\n2. When almost done, add milk\n3. Let it boil over (auspicious!)\n4. Add melted jaggery, cardamom\n5. Fry cashews in ghee, add to pongal\n6. Decorate serving pot with sugarcane","Traditionally cooked outdoors in a new clay pot.","Thai Pongal is the Tamil harvest thanksgiving. The milk must boil over for good fortune."))
R.append(m(378,"Sinhalese New Year Aasmi","festival","hard",30,20,10,"Western Province",0,[("rice flour","1 cup"),("coconut milk","1/2 cup"),("treacle","3/4 cup"),("oil for frying","3 cups")],"1. Make thin batter with rice flour and coconut milk\n2. Heat oil, pour batter through perforated coconut shell\n3. Form a lacy net pattern in oil\n4. Fry until lightly golden\n5. Remove, drizzle warm treacle\n6. Fold into quarters while still warm","The batter must be very thin to create the lacy pattern.","Aasmi is a delicate, lace-like sweet made for the Sinhala New Year table. Its intricate pattern represents the skill of the cook."))
R.append(m(379,"Easter Hot Cross Buns","festival","medium",60,20,12,"Western Province",0,[("flour","3 cups"),("yeast","2 tsp"),("sugar","1/4 cup"),("butter","50g"),("milk","1 cup"),("egg","1"),("mixed spice","1 tsp"),("cinnamon","1/2 tsp"),("raisins","1/2 cup"),("mixed peel","2 tbsp")],"1. Dissolve yeast in warm milk with sugar\n2. Mix flour, spices, add yeast mixture, egg, butter\n3. Knead 10 mins, add raisins and peel\n4. Prove 1 hour until doubled\n5. Shape into 12 buns, prove again 20 mins\n6. Pipe crosses with flour paste, bake 200C for 15-20 mins","Prove in a warm spot for best rise.","Hot cross buns are a Christian Easter tradition in Sri Lanka, especially in Burgher and Catholic communities."))
R.append(m(380,"Ganesh Chaturthi Modaks","festival","medium",30,20,8,"Northern Province",0,[("rice flour","2 cups"),("grated coconut","1 cup"),("jaggery","3/4 cup"),("cardamom","1/4 tsp"),("nutmeg","pinch"),("water","1.5 cups"),("ghee","1 tbsp")],"1. Make filling: cook coconut and jaggery until combined, add spices\n2. Boil water, add rice flour off heat, knead smooth dough\n3. Make small cups from dough\n4. Fill with coconut-jaggery mixture\n5. Pinch top together to seal in teardrop shape\n6. Steam for 10-15 minutes","Keep dough covered with damp cloth to prevent drying.","Modaks are sweet dumplings offered to Lord Ganesh during the Hindu festival of Ganesh Chaturthi."))

# BEVERAGES (10) SL_0381-0390
R.append(m(381,"Faluda","beverage","easy",10,5,2,"Island-wide",0,[("falooda seeds","1 tbsp"),("falooda noodles","1/4 cup"),("milk","400ml"),("rose syrup","3 tbsp"),("sugar","2 tbsp"),("ice cream","1 scoop"),("crushed ice","1 cup")],"1. Soak falooda seeds in water until swollen\n2. Cook falooda noodles, rinse in cold water\n3. Mix milk with rose syrup and sugar\n4. Layer in glass: noodles, seeds, crushed ice\n5. Pour rose milk over\n6. Top with ice cream and drizzle of rose syrup","Use high-quality rose syrup for authentic pink color and fragrance.","Faluda is Sri Lanka's favorite sweet drink-dessert, sold at every corner shop especially during hot weather."))
R.append(m(382,"King Coconut Water (Thambili)","beverage","easy",2,0,1,"Island-wide",0,[("king coconut","1")],"1. Select a fresh, bright orange king coconut\n2. Cut the top with a sharp machete\n3. Insert a straw\n4. Drink the refreshing water directly\n5. After drinking, scoop out soft flesh to eat\n6. Best served chilled","Choose heavy king coconuts - they have more water inside.","King coconut (thambili) is Sri Lanka's iconic natural energy drink. Roadside thambili sellers are a ubiquitous sight across the island."))
R.append(m(383,"Wood Apple Juice","beverage","easy",10,0,2,"Island-wide",0,[("wood apple","1 large"),("sugar","3 tbsp"),("water","2 cups"),("ice","as needed")],"1. Crack open the hard wood apple shell\n2. Scoop out the brown pulp\n3. Add to water, mix and squeeze through strainer\n4. Add sugar, stir until dissolved\n5. Add ice\n6. Serve chilled","Strain well to remove seeds and fibrous bits.","Wood apple juice is a beloved Sri Lankan drink with a distinctive tangy-sweet flavor found nowhere else in the world."))
R.append(m(384,"Ceylon Tea (Plain Tea)","beverage","easy",5,5,2,"Central Province",0,[("Ceylon black tea leaves","2 tsp"),("water","2 cups"),("sugar","to taste")],"1. Boil fresh water\n2. Add tea leaves to pot\n3. Pour boiling water over leaves\n4. Steep 3-4 minutes\n5. Strain into cups\n6. Add sugar if desired","Use freshly boiled water and never re-boil for best flavor.","Ceylon tea is Sri Lanka's most famous export. The tea of the Central Highlands is considered among the finest in the world."))
R.append(m(385,"Milk Tea (Kiri Te)","beverage","easy",5,5,2,"Island-wide",0,[("Ceylon black tea","2 tsp"),("water","1 cup"),("milk","1 cup"),("sugar","2 tsp")],"1. Boil water, add tea leaves\n2. Brew strong tea for 3-4 minutes\n3. Strain into cup\n4. Add hot milk\n5. Add sugar, stir well\n6. Serve hot","Brew the tea stronger than usual since milk dilutes it.","Kiri te (milk tea) is the lifeblood of Sri Lanka. It is offered to every visitor and consumed multiple times daily."))
R.append(m(386,"Ginger Beer","beverage","easy",15,20,4,"Island-wide",1,[("fresh ginger","100g"),("sugar","1 cup"),("lime juice","2 tbsp"),("water","4 cups"),("cloves","3"),("cinnamon stick","1")],"1. Peel and grate ginger\n2. Boil water with ginger, cloves, cinnamon 15 mins\n3. Strain, add sugar while hot\n4. Add lime juice\n5. Cool completely\n6. Serve over ice","Use old ginger for stronger flavor.","Ginger beer is Sri Lanka's original soft drink, made at home long before commercial beverages arrived."))
R.append(m(387,"Belimal (Bael Fruit Drink)","beverage","easy",10,0,2,"Island-wide",0,[("bael fruit","1"),("sugar","3 tbsp"),("water","2 cups"),("ice","as needed")],"1. Scoop out bael fruit pulp\n2. Add water and mash well\n3. Strain through sieve\n4. Add sugar and stir\n5. Add ice\n6. Serve chilled","Choose ripe bael fruit with cracks on the shell.","Belimal is a traditional cooling drink believed to aid digestion and soothe the stomach in Ayurvedic medicine."))
R.append(m(388,"Kurumba (Young Coconut) Smoothie","beverage","easy",5,0,2,"Southern Province",0,[("young coconut water","1 cup"),("young coconut flesh","1/2 cup"),("condensed milk","2 tbsp"),("ice","1 cup")],"1. Extract water and scoop flesh from young coconut\n2. Add coconut water, flesh, condensed milk to blender\n3. Add ice\n4. Blend until smooth\n5. Pour into glass\n6. Serve immediately","Use green tender coconuts for the softest flesh.","Young coconut smoothies are a beach-side treat especially popular in Southern coastal tourist areas."))
R.append(m(389,"Nelli Juice (Indian Gooseberry)","beverage","easy",10,5,2,"Island-wide",0,[("nelli (amla)","10"),("sugar","3 tbsp"),("water","2 cups"),("salt","pinch"),("ice","as needed")],"1. Wash and chop nelli, remove seeds\n2. Blend with water until smooth\n3. Strain through fine sieve\n4. Add sugar, pinch of salt\n5. Stir well, add ice\n6. Serve immediately before oxidation","Drink immediately - nelli juice oxidizes and turns brown quickly.","Nelli juice is one of the richest sources of vitamin C. Sri Lankan grandmothers swear by it for immunity and glowing skin."))
R.append(m(390,"Coriander and Mint Cooler","beverage","easy",10,0,2,"Eastern Province",0,[("fresh coriander","1 cup"),("fresh mint","1/2 cup"),("green chili","1"),("lime juice","2 tbsp"),("sugar","2 tbsp"),("water","2 cups"),("salt","pinch"),("ice","as needed")],"1. Wash herbs thoroughly\n2. Blend coriander, mint, green chili with water\n3. Strain through fine sieve\n4. Add lime juice, sugar, salt\n5. Mix well, add ice\n6. Serve as a refreshing cooler","Use fresh, vibrant green herbs for best flavor and color.","This herbal cooler is a refreshing drink popular in the Eastern Province, especially during Ramadan as an iftar drink."))

with open("generate_recipes_data_p4.json","w",encoding="utf-8") as f:
    json.dump(R, f, indent=2, ensure_ascii=False)
print(f"Part 4: {len(R)} recipes (snacks+festival+beverages SL_0341-SL_0390) saved")
