"""Generate Sri Lankan recipes Part 1: Curries (45), Rice (25), Breakfast (25) = 95 recipes"""
import json

def make(id_num, name, cat, diff, prep, cook, serv, region, spice, ings, method, tips, note):
    return {
        "id": f"SL_{id_num:04d}",
        "names": {"english": name},
        "category": cat, "difficulty": diff,
        "prep_time_mins": prep, "cook_time_mins": cook, "servings": serv,
        "region": region, "spice_level": spice, "is_authentic": True,
        "ingredients": [{"name": n, "amount": a} for n, a in ings],
        "method": method, "tips": tips, "cultural_note": note
    }

recipes = []
# === CURRIES (45) SL_0191 - SL_0235 ===
recipes.append(make(191,"Ambulthiyal (Sour Fish Curry)","curry","medium",20,40,4,"Southern Province",3,[("tuna steaks","500g"),("goraka (garcinia cambogia)","30g"),("black pepper","1 tsp"),("curry leaves","1 sprig"),("turmeric powder","1/2 tsp"),("salt","to taste"),("pandan leaves","2"),("garlic","4 cloves")],"1. Clean and cut tuna into large cubes\n2. Soak goraka in warm water for 10 minutes, then grind to paste\n3. Coat fish with goraka paste, turmeric, pepper and salt\n4. Place in a clay pot with curry leaves and pandan leaves\n5. Cook on low heat without water for 30-40 minutes, turning occasionally\n6. The fish will release its own moisture and become dark and dry","Use thick tuna steaks for best results. Do not add water - the fish cooks in its own juices.","Ambulthiyal is the signature dish of Southern Sri Lanka, especially Galle and Matara. The goraka acts as a natural preservative, allowing the dish to last several days without refrigeration."))

recipes.append(make(192,"Jaffna Crab Curry","curry","hard",30,45,4,"Northern Province",4,[("mud crabs","1 kg"),("onion","2 large"),("tomato","2"),("curry leaves","2 sprigs"),("Jaffna curry powder","3 tbsp"),("chili powder","1 tbsp"),("turmeric","1 tsp"),("fenugreek seeds","1/2 tsp"),("coconut milk","400ml"),("tamarind paste","1 tbsp"),("garlic","6 cloves"),("ginger","1 inch")],"1. Clean crabs, remove top shell, cut in half and crack claws\n2. Heat oil, add fenugreek seeds until they pop\n3. Saute onions, garlic, ginger until golden\n4. Add tomatoes, curry powder, chili, turmeric, cook 5 mins\n5. Add crabs and tamarind paste, stir to coat\n6. Pour in coconut milk, add curry leaves, cover and simmer 25-30 minutes","Select heavy crabs with firm shells for the meatiest results. Crack claws before cooking so the curry penetrates.","Jaffna crab curry is world-renowned and considered one of Sri Lanka's finest dishes. The Jaffna Peninsula's lagoons provide exceptional mud crabs that make this curry uniquely flavorful."))

recipes.append(make(193,"Mutton Curry (Aatu Kari)","curry","medium",20,90,6,"Central Province",3,[("mutton","750g"),("onion","3 large"),("curry powder","3 tbsp"),("chili powder","1 tsp"),("turmeric","1/2 tsp"),("cardamom","4 pods"),("cloves","4"),("cinnamon stick","1 piece"),("curry leaves","2 sprigs"),("coconut milk","500ml"),("potato","2 medium"),("tomato","2"),("garlic","6 cloves"),("ginger","1.5 inch")],"1. Marinate mutton with curry powder, chili, turmeric, salt for 30 mins\n2. Heat oil, add whole spices (cardamom, cloves, cinnamon) until fragrant\n3. Saute onions, garlic, ginger until brown\n4. Add marinated mutton, cook on high heat for 10 minutes\n5. Add tomatoes and thin coconut milk, cover and simmer 60 mins\n6. Add potatoes and thick coconut milk, cook 20 more minutes until tender","Slow cooking on low heat is essential. The mutton should be falling off the bone when done.","Mutton curry is a celebration dish in Sri Lanka, commonly served at weddings, religious festivals, and special occasions across all communities."))

recipes.append(make(194,"Polos Curry (Green Jackfruit Curry)","curry","medium",25,50,4,"Western Province",2,[("green jackfruit","500g"),("onion","1 large"),("curry powder","2 tbsp"),("turmeric","1/2 tsp"),("chili powder","1 tsp"),("coconut milk","300ml"),("curry leaves","1 sprig"),("pandan leaves","2"),("Maldive fish","1 tbsp"),("mustard seeds","1/2 tsp"),("garlic","3 cloves"),("fenugreek seeds","1/4 tsp")],"1. Cut jackfruit into small pieces, remove seeds\n2. Boil jackfruit with turmeric and salt until half cooked\n3. Heat oil, add mustard and fenugreek seeds until they pop\n4. Saute onions and garlic until soft\n5. Add spices, Maldive fish, curry leaves, pandan leaves\n6. Add jackfruit and coconut milk, simmer 25-30 minutes until thick","Oil your hands before cutting raw jackfruit to prevent sticky latex from sticking to your skin.","Polos curry is a beloved vegetarian curry that mimics the texture of meat. It is a staple during the Buddhist Lent period when many Sri Lankans avoid meat."))

recipes.append(make(195,"Ela Batu Curry (Pea Eggplant Curry)","curry","easy",10,30,4,"Sabaragamuwa",2,[("pea eggplants (ela batu)","250g"),("onion","1"),("green chili","3"),("curry powder","1 tbsp"),("turmeric","1/4 tsp"),("coconut milk","200ml"),("Maldive fish","1 tbsp"),("curry leaves","1 sprig"),("garlic","2 cloves"),("goraka","1 piece")],"1. Wash pea eggplants and pierce each one with a knife\n2. Heat oil, saute onions, garlic, green chilies\n3. Add curry powder, turmeric, Maldive fish\n4. Add eggplants, goraka, and thin coconut milk\n5. Cook on medium heat 20 minutes until eggplants are soft\n6. Add thick coconut milk, simmer 5 minutes","Pierce the eggplants so curry flavor penetrates inside. Use goraka for authentic sour taste.","Ela batu is a tiny variety of eggplant unique to Sri Lanka and South India. This curry is considered very healthy and is a common accompaniment to rice and curry meals."))

recipes.append(make(196,"Kukul Mas Curry (Village-Style Chicken)","curry","medium",20,50,6,"Uva Province",3,[("free-range chicken","1 kg"),("onion","2"),("curry powder","3 tbsp"),("roasted curry powder","1 tbsp"),("chili powder","1.5 tsp"),("turmeric","1/2 tsp"),("coconut milk","400ml"),("curry leaves","2 sprigs"),("pandan leaves","2"),("cinnamon stick","1"),("cardamom","3 pods"),("garlic","5 cloves"),("ginger","1 inch"),("tomato","1")],"1. Cut chicken into pieces, marinate with curry powder, turmeric, salt\n2. Heat oil, add cinnamon and cardamom\n3. Saute onions until deep golden brown\n4. Add garlic, ginger, tomato, chili powder\n5. Add chicken, cook 10 mins on high, then add coconut milk\n6. Cover and simmer 30-35 minutes, finish with roasted curry powder","Use village (free-range) chicken for authentic flavor. The meat is tougher but far more flavorful.","This village-style chicken curry from Uva Province uses traditional wood-fire cooking methods. The slow cooking in a clay pot gives it an earthy, smoky flavor unique to rural Sri Lankan kitchens."))

recipes.append(make(197,"Dhall Curry with Spinach","curry","easy",10,25,4,"Island-wide",1,[("red lentils","1 cup"),("spinach","2 cups"),("onion","1"),("tomato","1"),("green chili","2"),("turmeric","1/2 tsp"),("coconut milk","200ml"),("curry leaves","1 sprig"),("mustard seeds","1/2 tsp"),("garlic","2 cloves"),("cumin seeds","1/4 tsp")],"1. Wash lentils, boil with turmeric until soft and mushy\n2. Heat oil, add mustard and cumin seeds until they pop\n3. Saute onions, garlic, green chilies until soft\n4. Add tomato, curry leaves, cook 3 minutes\n5. Add boiled lentils and washed spinach\n6. Pour in coconut milk, simmer 10 minutes, season with salt","Stir the lentils frequently to prevent sticking. The spinach wilts quickly so add it last.","Dhall curry is eaten daily in almost every Sri Lankan household. Adding spinach is a modern nutritional enhancement that many health-conscious families now practice."))

recipes.append(make(198,"Cadju Maluwa (Cashew Curry)","curry","medium",15,35,4,"North Western",2,[("raw cashew nuts","250g"),("onion","1"),("curry powder","2 tbsp"),("turmeric","1/2 tsp"),("chili powder","1 tsp"),("coconut milk","300ml"),("curry leaves","1 sprig"),("pandan leaves","1"),("cinnamon stick","1 small piece"),("garlic","3 cloves"),("Maldive fish","1 tbsp")],"1. Soak cashews in water for 2 hours or boil for 15 minutes\n2. Heat oil, saute onions and garlic until soft\n3. Add curry powder, chili, turmeric, Maldive fish\n4. Add drained cashews, stir to coat with spices\n5. Pour in thin coconut milk, cook 15-20 minutes\n6. Add thick coconut milk, pandan leaf, simmer 5 minutes","Pre-soaking cashews ensures they cook evenly and become creamy.","Cashew curry is a premium dish often served at weddings and special events. Sri Lanka's North Western Province (Puttalam) is the heart of the country's cashew production."))

recipes.append(make(199,"Beetroot Curry","curry","easy",15,25,4,"Island-wide",1,[("beetroot","3 medium"),("onion","1"),("green chili","2"),("curry powder","1 tbsp"),("turmeric","1/4 tsp"),("coconut milk","200ml"),("mustard seeds","1/2 tsp"),("curry leaves","1 sprig"),("Maldive fish","1 tbsp"),("desiccated coconut","2 tbsp")],"1. Peel and dice beetroot into small cubes\n2. Boil beetroot with turmeric until half cooked\n3. Heat oil, add mustard seeds until they pop\n4. Saute onions, green chilies, curry leaves\n5. Add beetroot, curry powder, Maldive fish, coconut\n6. Add coconut milk, simmer until beetroot is tender","Wear gloves when handling beetroot to avoid staining your hands.","Beetroot curry is a colorful addition to the traditional rice and curry plate. Its natural sweetness complements the spicier curries on the table."))

recipes.append(make(200,"Brinjal Moju (Eggplant Pickle Curry)","curry","easy",15,30,4,"Western Province",3,[("eggplant","500g"),("onion","2"),("green chili","4"),("mustard seeds","1 tsp"),("vinegar","3 tbsp"),("sugar","2 tbsp"),("chili powder","1 tsp"),("turmeric","1/4 tsp"),("curry leaves","1 sprig"),("oil for frying","1 cup"),("garlic","4 cloves"),("ginger","1 inch")],"1. Cut eggplant into thick rounds, sprinkle with turmeric and salt\n2. Deep fry eggplant slices until golden, set aside\n3. In a pan, add mustard seeds until they pop\n4. Saute onions, garlic, ginger, green chilies until caramelized\n5. Add vinegar, sugar, chili powder, cook 3 minutes\n6. Gently fold in fried eggplant, coat with the sauce","The sweet-sour-spicy balance is key. Adjust vinegar and sugar to your taste.","Brinjal moju is a beloved Sri Lankan pickle-style curry that reflects Dutch colonial influence. It is a must-have at Sinhala and Tamil New Year celebrations."))

recipes.append(make(201,"Squid Curry (Della Curry)","curry","medium",20,30,4,"Southern Province",3,[("squid","500g"),("onion","2"),("tomato","1"),("curry powder","2 tbsp"),("chili powder","1 tsp"),("turmeric","1/2 tsp"),("coconut milk","300ml"),("curry leaves","1 sprig"),("goraka","2 pieces"),("garlic","4 cloves"),("ginger","1 inch"),("fenugreek seeds","1/4 tsp")],"1. Clean squid, remove ink sac, cut into rings\n2. Heat oil, add fenugreek seeds until fragrant\n3. Saute onions, garlic, ginger until golden\n4. Add tomato, curry powder, chili, turmeric\n5. Add squid rings and goraka, cook 5 minutes on high\n6. Pour in coconut milk, simmer 15-20 minutes","Do not overcook squid or it becomes rubbery. 15-20 minutes is ideal.","Squid curry is a coastal delicacy especially popular in fishing villages along the southern coast of Sri Lanka."))

recipes.append(make(202,"Snake Gourd Curry","curry","easy",10,25,4,"North Central",1,[("snake gourd","500g"),("onion","1"),("green chili","2"),("curry powder","1 tbsp"),("turmeric","1/4 tsp"),("coconut milk","200ml"),("Maldive fish","1 tbsp"),("mustard seeds","1/2 tsp"),("curry leaves","1 sprig")],"1. Cut snake gourd into 1-inch pieces, remove seeds\n2. Heat oil, add mustard seeds until they pop\n3. Saute onions and green chilies\n4. Add snake gourd, curry powder, turmeric, Maldive fish\n5. Add thin coconut milk, cook 15-20 minutes until soft\n6. Add thick coconut milk, simmer 5 minutes","Choose young tender snake gourds for best results.","Snake gourd is one of the most commonly grown vegetables in Sri Lankan home gardens, making this curry a true household staple."))

recipes.append(make(203,"Bitter Gourd Curry (Karawila)","curry","medium",20,30,4,"Island-wide",2,[("bitter gourd","400g"),("onion","1"),("green chili","3"),("curry powder","1 tbsp"),("turmeric","1/4 tsp"),("coconut milk","200ml"),("Maldive fish","1 tbsp"),("mustard seeds","1/2 tsp"),("curry leaves","1 sprig"),("tamarind paste","1 tsp"),("sugar","1 tsp")],"1. Slice bitter gourd thinly, rub with salt and turmeric\n2. Squeeze out bitter juice, rinse and drain\n3. Deep fry slices until crispy, set aside\n4. Saute onions, mustard seeds, curry leaves\n5. Add spices, tamarind, sugar, Maldive fish\n6. Add fried bitter gourd and coconut milk, simmer 10 minutes","Salting and squeezing removes most of the bitterness while retaining the health benefits.","Karawila is highly valued in Sri Lankan traditional medicine (Ayurveda) for its blood sugar-regulating properties. Despite its bitter taste, it is enjoyed across the island."))

recipes.append(make(204,"Mushroom Curry","curry","easy",10,25,4,"Central Province",2,[("oyster mushrooms","400g"),("onion","1"),("tomato","1"),("curry powder","1.5 tbsp"),("chili powder","1/2 tsp"),("turmeric","1/4 tsp"),("coconut milk","200ml"),("curry leaves","1 sprig"),("garlic","3 cloves"),("black pepper","1/2 tsp")],"1. Clean and tear mushrooms into bite-sized pieces\n2. Heat oil, saute onions and garlic\n3. Add tomato, curry powder, chili, turmeric, pepper\n4. Add mushrooms, stir-fry 3 minutes\n5. Pour in coconut milk, add curry leaves\n6. Simmer 15 minutes until sauce thickens","Do not wash mushrooms under running water; wipe with a damp cloth instead.","Mushroom cultivation has become increasingly popular in Sri Lanka's hill country, making this curry a modern addition to the traditional rice and curry spread."))

recipes.append(make(205,"Ala Thel Dala (Spicy Potato Curry)","curry","easy",10,25,4,"Island-wide",2,[("potato","500g"),("onion","1"),("curry powder","1.5 tbsp"),("chili powder","1 tsp"),("turmeric","1/2 tsp"),("coconut milk","200ml"),("mustard seeds","1/2 tsp"),("curry leaves","1 sprig"),("Maldive fish","1 tbsp"),("garlic","3 cloves")],"1. Peel and cube potatoes\n2. Heat oil, add mustard seeds until they pop\n3. Saute onions and garlic until golden\n4. Add curry powder, chili, turmeric, Maldive fish\n5. Add potatoes and thin coconut milk\n6. Cover and cook 20 minutes until potatoes are tender","Cut potatoes into uniform sizes for even cooking.","Potato curry is a universal favorite in Sri Lanka, served at every rice and curry meal. The style varies by region - Southern style is drier while Western Province prefers it with more gravy."))

recipes.append(make(206,"Malu Mirisata (Fish in Red Sauce)","curry","medium",15,30,4,"Southern Province",4,[("seer fish","500g"),("onion","2"),("tomato","2"),("chili powder","2 tbsp"),("chili flakes","1 tbsp"),("turmeric","1/2 tsp"),("curry leaves","2 sprigs"),("pandan leaves","2"),("garlic","5 cloves"),("ginger","1 inch"),("vinegar","1 tbsp"),("goraka","2 pieces")],"1. Rub fish with turmeric and salt, set aside 10 minutes\n2. Heat oil, saute onions until brown\n3. Add garlic, ginger, tomatoes\n4. Add chili powder, chili flakes, goraka\n5. Add fish pieces carefully, add vinegar\n6. Cook 15-20 minutes on medium heat without stirring","Use firm fish like seer or tuna that won't break apart during cooking.","Malu mirisata is the fiery red fish curry of Sri Lanka's Southern coast. Fishermen's wives traditionally prepare this with the day's fresh catch."))

recipes.append(make(207,"Prawn Curry (Isso Curry)","curry","medium",20,25,4,"Western Province",3,[("prawns","500g"),("onion","1"),("tomato","1"),("curry powder","2 tbsp"),("chili powder","1 tsp"),("turmeric","1/2 tsp"),("coconut milk","300ml"),("curry leaves","1 sprig"),("fenugreek seeds","1/4 tsp"),("garlic","4 cloves"),("tamarind paste","1 tsp")],"1. Clean and devein prawns, keep tails on\n2. Heat oil, add fenugreek seeds\n3. Saute onions and garlic until soft\n4. Add tomato, all spices, and tamarind paste\n5. Add prawns, cook 3-4 minutes until pink\n6. Pour in coconut milk, simmer 10 minutes","Do not overcook prawns - they cook very quickly and become tough if overcooked.","Prawn curry is a luxurious dish typically prepared for special occasions. Sri Lanka's coastal areas, especially Negombo, are famous for their fresh prawns."))

recipes.append(make(208,"Ash Plantain Curry (Alu Kesel Curry)","curry","easy",10,30,4,"Sabaragamuwa",2,[("ash plantain","3"),("onion","1"),("curry powder","1.5 tbsp"),("chili powder","1/2 tsp"),("turmeric","1/4 tsp"),("coconut milk","300ml"),("mustard seeds","1/2 tsp"),("curry leaves","1 sprig"),("Maldive fish","1 tbsp"),("pandan leaves","1")],"1. Peel plantains, cut into thick rounds\n2. Rub with turmeric and salt\n3. Heat oil, add mustard seeds until they pop\n4. Saute onions, curry leaves, pandan leaf\n5. Add plantain, spices, Maldive fish, thin coconut milk\n6. Cook 20 minutes, add thick coconut milk, simmer 5 more minutes","Use mature ash plantains (not sweet bananas) for this curry.","Ash plantain curry is one of the most affordable and beloved vegetable curries in Sri Lanka. It is available year-round and pairs perfectly with rice."))

recipes.append(make(209,"Cuttlefish Curry (Dhallo Curry)","curry","medium",15,30,4,"Eastern Province",3,[("cuttlefish","500g"),("onion","2"),("tomato","1"),("curry powder","2 tbsp"),("chili powder","1 tsp"),("turmeric","1/2 tsp"),("coconut milk","300ml"),("curry leaves","1 sprig"),("fenugreek seeds","1/4 tsp"),("garlic","4 cloves"),("ginger","1 inch"),("vinegar","1 tsp")],"1. Clean cuttlefish, remove bone and ink, cut into pieces\n2. Heat oil, add fenugreek, saute onions, garlic, ginger\n3. Add tomato, curry powder, chili and turmeric\n4. Add cuttlefish, vinegar, cook 5 minutes\n5. Pour in thin coconut milk, simmer 20 minutes\n6. Add thick coconut milk, curry leaves, cook 5 more minutes","Score the cuttlefish in a crosshatch pattern so it curls beautifully while cooking.","Cuttlefish curry is popular in Trincomalee and Batticaloa on Sri Lanka's eastern coast, where fresh cuttlefish is abundant."))

recipes.append(make(210,"Bonchi Curry (Green Bean Curry)","curry","easy",10,20,4,"Island-wide",1,[("green beans","400g"),("onion","1"),("desiccated coconut","3 tbsp"),("curry powder","1 tbsp"),("turmeric","1/4 tsp"),("chili powder","1/2 tsp"),("coconut milk","150ml"),("Maldive fish","1 tbsp"),("mustard seeds","1/2 tsp"),("curry leaves","1 sprig")],"1. Cut green beans into 1-inch pieces\n2. Heat oil, add mustard seeds until they pop\n3. Saute onions and curry leaves\n4. Add beans, spices, Maldive fish, desiccated coconut\n5. Add coconut milk, cover and cook 15-20 minutes\n6. Season with salt, stir gently","Use fresh tender beans for the best texture.","Green bean curry is one of the simplest yet most satisfying Sri Lankan curries, commonly prepared for daily home meals."))

recipes.append(make(211,"Pumpkin Curry (Wattakka Curry)","curry","easy",10,25,4,"North Central",1,[("pumpkin","500g"),("onion","1"),("curry powder","1 tbsp"),("chili powder","1/2 tsp"),("turmeric","1/4 tsp"),("coconut milk","200ml"),("mustard seeds","1/2 tsp"),("curry leaves","1 sprig"),("Maldive fish","1 tbsp"),("sugar","1 tsp")],"1. Peel pumpkin, cut into bite-sized cubes\n2. Heat oil, add mustard seeds\n3. Saute onions and curry leaves\n4. Add pumpkin, spices, Maldive fish\n5. Add coconut milk, cover and cook 20 minutes\n6. Add sugar to balance the flavor","Choose orange-fleshed pumpkin for naturally sweet curry.","Pumpkin curry with its natural sweetness provides a wonderful contrast to spicy curries on the Sri Lankan plate."))

recipes.append(make(212,"Dried Fish Curry (Karawala Curry)","curry","easy",15,30,4,"Southern Province",4,[("dried fish (Maldive tuna)","200g"),("onion","2"),("tomato","1"),("chili powder","2 tbsp"),("curry powder","1 tbsp"),("turmeric","1/4 tsp"),("coconut milk","200ml"),("tamarind","1 tbsp"),("curry leaves","1 sprig"),("garlic","4 cloves"),("goraka","2 pieces")],"1. Soak dried fish in water 30 minutes, drain and clean\n2. Cut into pieces, fry lightly in oil\n3. Saute onions, garlic until brown\n4. Add tomato, chili, curry powder, turmeric\n5. Add dried fish, goraka, tamarind, thin coconut milk\n6. Simmer 20 minutes until sauce thickens","Soak and wash dried fish well to remove excess salt.","Dried fish curry is a pantry staple in Sri Lanka, providing protein in areas far from the coast. It continues to be one of the most economical sources of protein for rural families."))

recipes.append(make(213,"Drumstick Curry (Murunga Curry)","curry","easy",10,30,4,"Northern Province",2,[("drumsticks","6 sticks"),("onion","1"),("curry powder","1.5 tbsp"),("chili powder","1/2 tsp"),("turmeric","1/4 tsp"),("coconut milk","200ml"),("Maldive fish","1 tbsp"),("mustard seeds","1/2 tsp"),("curry leaves","1 sprig"),("garlic","3 cloves")],"1. Cut drumsticks into 3-inch pieces\n2. Heat oil, add mustard seeds\n3. Saute onions, garlic, curry leaves\n4. Add spices and Maldive fish\n5. Add drumsticks and thin coconut milk\n6. Cook 25 minutes until drumstick flesh is soft","You eat drumsticks by scraping the soft flesh from the fibrous outer shell with your teeth.","Moringa (murunga) is called a superfood and is grown in almost every Sri Lankan garden. The curry made from its pods is nutritious and medicinal."))

recipes.append(make(214,"Sardine Curry","curry","easy",10,25,4,"Western Province",3,[("fresh sardines","500g"),("onion","1"),("tomato","1"),("curry powder","2 tbsp"),("chili powder","1 tsp"),("turmeric","1/2 tsp"),("coconut milk","200ml"),("goraka","2 pieces"),("curry leaves","1 sprig"),("garlic","3 cloves"),("ginger","1/2 inch")],"1. Clean sardines, rub with turmeric and salt\n2. Place in a clay pot with sliced onions, garlic, ginger\n3. Add tomato, curry powder, chili, goraka\n4. Pour thin coconut milk over fish\n5. Cook on medium heat 15-20 minutes\n6. Add thick coconut milk, simmer 5 minutes","Do not stir the curry - gently shake the pot to prevent fish from breaking.","Sardine curry is the everyday fish curry of Sri Lanka, affordable and nutritious. It is best cooked in a traditional clay pot."))

recipes.append(make(215,"Leeks Curry","curry","easy",10,20,4,"Central Province",1,[("leeks","500g"),("onion","1"),("chili powder","1/2 tsp"),("curry powder","1 tbsp"),("turmeric","1/4 tsp"),("coconut milk","150ml"),("Maldive fish","1 tbsp"),("mustard seeds","1/2 tsp"),("curry leaves","1 sprig"),("black pepper","1/4 tsp")],"1. Wash leeks thoroughly, cut into 1-inch pieces\n2. Heat oil, add mustard seeds\n3. Saute onions and curry leaves\n4. Add leeks, spices, Maldive fish, pepper\n5. Add coconut milk, cook 15 minutes\n6. Season with salt","Clean leeks by slicing lengthwise and washing between layers to remove sand.","Leeks grow prolifically in Sri Lanka's hill country around Nuwara Eliya, making this a beloved vegetable curry of the Central Province."))

recipes.append(make(216,"Mango Curry (Amba Maluwa)","curry","easy",10,25,4,"North Western",2,[("raw green mangoes","3"),("onion","1"),("chili powder","1 tsp"),("curry powder","1 tbsp"),("turmeric","1/4 tsp"),("coconut milk","200ml"),("sugar","2 tsp"),("mustard seeds","1/2 tsp"),("curry leaves","1 sprig"),("Maldive fish","1 tbsp")],"1. Peel green mangoes, cut into chunks\n2. Heat oil, add mustard seeds\n3. Saute onions and curry leaves\n4. Add mango pieces, spices, Maldive fish\n5. Add coconut milk and sugar\n6. Simmer 20 minutes until mango is soft","Use unripe, sour mangoes for authentic flavor. The sugar balances the tartness.","Mango curry is a seasonal delicacy prepared during the mango season (May-July). Its sweet-sour flavor is a unique addition to the Sri Lankan spread."))

recipes.append(make(217,"Tinned Fish Curry","curry","easy",5,20,4,"Island-wide",2,[("canned mackerel","2 cans"),("onion","1"),("tomato","1"),("chili powder","1 tsp"),("curry powder","1 tbsp"),("turmeric","1/4 tsp"),("coconut milk","150ml"),("curry leaves","1 sprig"),("garlic","3 cloves"),("green chili","2")],"1. Drain canned fish, break into large chunks\n2. Heat oil, saute onions, garlic, green chilies\n3. Add tomato, curry powder, chili, turmeric\n4. Gently add fish chunks\n5. Pour in coconut milk, add curry leaves\n6. Simmer 10-15 minutes on low heat","Handle the fish gently to keep chunks intact. Do not stir vigorously.","Tinned fish curry is one of Sri Lanka's most popular quick meals, especially among students and working families. It is affectionately known as a comfort food."))

recipes.append(make(218,"Egg Curry (Bittara Curry)","curry","easy",10,25,4,"Island-wide",2,[("eggs","6"),("onion","1"),("tomato","1"),("curry powder","2 tbsp"),("chili powder","1 tsp"),("turmeric","1/2 tsp"),("coconut milk","200ml"),("curry leaves","1 sprig"),("garlic","3 cloves"),("ginger","1/2 inch")],"1. Hard boil eggs, peel and make small cuts on surface\n2. Deep fry eggs until golden, set aside\n3. Saute onions, garlic, ginger until soft\n4. Add tomato, spices, cook 3 minutes\n5. Add thin coconut milk, bring to simmer\n6. Add fried eggs, cook in curry 10-15 minutes","Score the eggs so the curry sauce penetrates for better flavor.","Egg curry is an economical protein-rich curry enjoyed across all social classes in Sri Lanka. It is a common alternative when meat is unavailable."))

recipes.append(make(219,"Devilled Chicken","curry","medium",15,20,4,"Island-wide",4,[("chicken","500g"),("onion","2"),("capsicum","1"),("tomato","1"),("chili powder","1 tbsp"),("chili flakes","1 tbsp"),("soy sauce","2 tbsp"),("tomato sauce","2 tbsp"),("garlic","5 cloves"),("ginger","1 inch"),("curry leaves","1 sprig"),("green chili","4"),("oil","3 tbsp")],"1. Cut chicken into bite-sized pieces, season with salt and turmeric\n2. Deep fry chicken pieces until golden, set aside\n3. Saute onions, garlic, ginger in hot oil\n4. Add capsicum, green chilies, tomato\n5. Add soy sauce, tomato sauce, chili powder, chili flakes\n6. Toss in fried chicken, mix well on high heat for 3-4 minutes","High heat stir-frying is essential for the smoky wok flavor Sri Lankans call 'thel piyawuna'.","Devilled dishes are a unique Sri Lankan invention - a fiery fusion of local spices with Chinese stir-fry techniques, popularized by Sri Lanka's Chinese restaurants."))

recipes.append(make(220,"Devilled Prawns","curry","medium",20,15,4,"Western Province",4,[("prawns","500g"),("onion","2"),("capsicum","1"),("tomato","1"),("chili powder","1 tbsp"),("chili flakes","2 tsp"),("soy sauce","2 tbsp"),("tomato sauce","1 tbsp"),("garlic","4 cloves"),("ginger","1 inch"),("curry leaves","1 sprig"),("green chili","4"),("vinegar","1 tsp")],"1. Clean and devein prawns\n2. Stir fry prawns in hot oil until just pink, remove\n3. In same wok, saute onions, garlic, ginger on high heat\n4. Add capsicum, green chilies, tomato\n5. Add all sauces, chili powder, chili flakes, vinegar\n6. Return prawns, toss vigorously for 2-3 minutes","Cook prawns briefly - they continue cooking in residual heat.","Devilled prawns is a star dish at Sri Lankan Chinese restaurants and is a must-order item at celebrations and parties."))

recipes.append(make(221,"Tempered Potatoes (Ala Theldala)","curry","easy",10,20,4,"Island-wide",2,[("potato","500g"),("onion","1"),("chili powder","1 tsp"),("turmeric","1/4 tsp"),("mustard seeds","1/2 tsp"),("curry leaves","1 sprig"),("Maldive fish","1 tbsp"),("green chili","2"),("desiccated coconut","2 tbsp"),("oil","2 tbsp")],"1. Boil potatoes until just cooked, peel and cube\n2. Heat oil, add mustard seeds until they pop\n3. Add onions, green chilies, curry leaves\n4. Add chili powder, turmeric, Maldive fish\n5. Add potato cubes, toss gently\n6. Sprinkle desiccated coconut, mix and serve","Use waxy potatoes that hold their shape after boiling.","Tempered potato is a dry curry preparation that is one of the most common side dishes served with rice and curry at any Sri Lankan meal."))

recipes.append(make(222,"Kooni Isso Curry (Tiny Shrimp Curry)","curry","easy",10,20,4,"Southern Province",3,[("tiny dried shrimp","200g"),("onion","1"),("chili powder","1.5 tsp"),("curry powder","1 tbsp"),("turmeric","1/4 tsp"),("coconut milk","200ml"),("tamarind","1 tsp"),("curry leaves","1 sprig"),("garlic","3 cloves"),("goraka","1 piece")],"1. Wash dried shrimp and soak for 10 minutes\n2. Heat oil, saute onions, garlic, curry leaves\n3. Add chili powder, curry powder, turmeric\n4. Add shrimp, goraka, and tamarind\n5. Pour in coconut milk\n6. Simmer 15 minutes until sauce thickens","Soak the dried shrimp to remove excess salt before cooking.","Kooni isso curry is a humble coastal curry that packs incredible umami flavor. It is a staple in fishing communities along Sri Lanka's coast."))

recipes.append(make(223,"Kiri Hodi (Coconut Milk Gravy)","curry","easy",5,20,4,"Island-wide",1,[("coconut milk","400ml"),("onion","1 small"),("green chili","2"),("turmeric","1/2 tsp"),("fenugreek seeds","1/4 tsp"),("curry leaves","1 sprig"),("pandan leaves","1"),("garlic","2 cloves"),("lime juice","1 tbsp"),("salt","to taste")],"1. Pour thin coconut milk into a pot\n2. Add sliced onion, garlic, green chilies, curry leaves, pandan\n3. Add turmeric, fenugreek seeds, salt\n4. Bring to a gentle simmer, cook 10 minutes\n5. Add thick coconut milk, simmer 5 more minutes\n6. Remove from heat, add lime juice","Never boil vigorously after adding thick coconut milk - it will split.","Kiri hodi is the gentle coconut milk gravy that accompanies hoppers, string hoppers, and pittu. It is a mild, soothing curry that balances the spicier dishes."))

recipes.append(make(224,"Parippu (Red Lentil Curry)","curry","easy",5,20,4,"Island-wide",1,[("red lentils","1 cup"),("onion","1 small"),("garlic","2 cloves"),("green chili","2"),("turmeric","1/2 tsp"),("coconut milk","200ml"),("curry leaves","1 sprig"),("mustard seeds","1/2 tsp"),("cumin seeds","1/4 tsp"),("Maldive fish","1 tbsp")],"1. Wash lentils until water runs clear\n2. Boil with turmeric and salt until soft\n3. Heat oil, temper mustard and cumin seeds\n4. Saute onions, garlic, green chilies\n5. Add curry leaves, Maldive fish\n6. Combine with lentils, add coconut milk, simmer 5 minutes","Wash lentils thoroughly to remove starch for better texture.","Parippu is arguably Sri Lanka's most essential curry. No rice and curry meal is complete without it. Every Sri Lankan learns to cook this first."))

recipes.append(make(225,"Lamb Curry","curry","hard",20,90,6,"Eastern Province",3,[("lamb shoulder","1 kg"),("onion","3"),("curry powder","3 tbsp"),("chili powder","1.5 tsp"),("turmeric","1/2 tsp"),("coconut milk","500ml"),("cinnamon stick","1"),("cardamom","4 pods"),("cloves","4"),("curry leaves","2 sprigs"),("tomato","2"),("garlic","8 cloves"),("ginger","2 inch"),("fennel seeds","1 tsp")],"1. Marinate lamb with spices for 1 hour\n2. Heat oil, add whole spices until fragrant\n3. Brown onions, garlic, ginger\n4. Add marinated lamb, sear on all sides\n5. Add tomatoes, thin coconut milk, simmer 1 hour\n6. Add thick coconut milk, cook 20 more minutes until tender","Marinating overnight gives the deepest flavor penetration.","Lamb curry is a celebratory dish in Sri Lanka's Muslim communities, especially in the Eastern Province, prepared for Eid and other festivals."))

recipes.append(make(226,"Gotukola Curry (Pennywort Curry)","curry","easy",15,15,4,"Island-wide",1,[("gotukola leaves","2 cups"),("onion","1 small"),("green chili","2"),("desiccated coconut","3 tbsp"),("Maldive fish","1 tbsp"),("lime juice","2 tbsp"),("salt","to taste"),("turmeric","1/4 tsp")],"1. Wash gotukola leaves thoroughly\n2. Finely chop the leaves\n3. Finely chop onion and green chilies\n4. Mix all ingredients together\n5. Add desiccated coconut, Maldive fish, turmeric\n6. Season with lime juice and salt","This is a raw preparation - no cooking needed. The lime juice 'cooks' the leaves slightly.","Gotukola (Centella asiatica) is revered in Ayurvedic medicine for improving brain function. This salad-like curry is eaten daily by health-conscious Sri Lankans."))

recipes.append(make(227,"Duck Curry","curry","hard",30,75,6,"North Western",3,[("duck","1 kg"),("onion","2"),("curry powder","3 tbsp"),("chili powder","1 tsp"),("turmeric","1/2 tsp"),("coconut milk","400ml"),("vinegar","2 tbsp"),("cinnamon stick","1"),("cardamom","3 pods"),("curry leaves","2 sprigs"),("garlic","6 cloves"),("ginger","1.5 inch"),("mustard seeds","1/2 tsp")],"1. Clean duck, cut into pieces, marinate with vinegar and spices\n2. Heat oil, add cinnamon, cardamom, mustard seeds\n3. Brown onions, garlic, ginger\n4. Add duck pieces, sear until browned\n5. Add coconut milk, curry leaves, cover and cook 60 minutes\n6. Uncover, reduce sauce until thick","Duck releases a lot of fat during cooking - skim excess fat for a lighter curry.","Duck curry is a special occasion dish in Sri Lanka, particularly popular in the North Western Province where duck farming is common."))

recipes.append(make(228,"Soya Meat Curry","curry","easy",15,25,4,"Island-wide",2,[("soya meat chunks","200g"),("onion","1"),("tomato","1"),("curry powder","2 tbsp"),("chili powder","1 tsp"),("turmeric","1/2 tsp"),("coconut milk","200ml"),("curry leaves","1 sprig"),("garlic","3 cloves"),("cinnamon stick","1 small piece")],"1. Soak soya chunks in hot water 15 minutes, squeeze dry\n2. Deep fry soya chunks until golden, set aside\n3. Saute onions, garlic, cinnamon\n4. Add tomato, curry powder, chili, turmeric\n5. Add fried soya chunks and coconut milk\n6. Simmer 15 minutes until sauce is absorbed","Squeeze out all water from soaked soya for better texture and flavor absorption.","Soya meat curry is a popular vegetarian protein alternative in Sri Lanka, especially during Buddhist Poya days when many avoid meat."))

recipes.append(make(229,"Canned Fish Tempered Dry Curry","curry","easy",5,15,4,"Island-wide",3,[("canned fish (mackerel)","1 can"),("onion","2"),("green chili","4"),("chili powder","1 tsp"),("chili flakes","1 tsp"),("turmeric","1/4 tsp"),("curry leaves","1 sprig"),("lime juice","1 tbsp"),("Maldive fish","1 tbsp"),("desiccated coconut","2 tbsp")],"1. Drain canned fish, flake into chunks\n2. Heat oil, saute onions until crispy\n3. Add green chilies, curry leaves\n4. Add chili powder, flakes, turmeric, Maldive fish\n5. Add fish, gently toss with spices\n6. Add coconut, lime juice, mix and serve","This is meant to be a dry curry - do not add coconut milk.","This quick dry curry is a favorite among Sri Lankan students and bachelors for its simplicity and bold flavors."))

recipes.append(make(230,"Breadfruit Curry (Del Curry)","curry","easy",15,35,4,"Western Province",2,[("breadfruit","500g"),("onion","1"),("curry powder","1.5 tbsp"),("chili powder","1/2 tsp"),("turmeric","1/4 tsp"),("coconut milk","300ml"),("mustard seeds","1/2 tsp"),("fenugreek seeds","1/4 tsp"),("curry leaves","1 sprig"),("Maldive fish","1 tbsp"),("pandan leaves","1")],"1. Peel breadfruit, remove core, cut into chunks\n2. Boil breadfruit with turmeric until half cooked\n3. Heat oil, add mustard and fenugreek seeds\n4. Saute onions, curry leaves\n5. Add breadfruit, spices, Maldive fish, coconut milk\n6. Simmer 20 minutes until tender and sauce thickens","Choose firm breadfruit that is not overripe for curry.","Breadfruit trees are found in every Sri Lankan village. The curry made from this starchy fruit is filling and economical, often replacing rice during times of scarcity."))

recipes.append(make(231,"Venison Curry","curry","hard",30,90,6,"Uva Province",4,[("venison","750g"),("onion","2"),("curry powder","3 tbsp"),("chili powder","2 tsp"),("turmeric","1/2 tsp"),("coconut milk","400ml"),("vinegar","2 tbsp"),("cinnamon stick","1"),("cardamom","4 pods"),("cloves","4"),("curry leaves","2 sprigs"),("garlic","8 cloves"),("ginger","2 inch"),("black pepper","1 tsp")],"1. Marinate venison with vinegar, spices, garlic, ginger overnight\n2. Heat oil, add whole spices\n3. Brown onions deeply\n4. Add marinated meat, sear on high heat\n5. Add thin coconut milk, simmer 90 minutes\n6. Add thick coconut milk, pepper, cook 15 more minutes","Overnight marination is essential to tenderize the gamey meat.","Venison curry is a traditional dish from Sri Lanka's Uva Province where deer farming exists. It has a rich, deep flavor distinct from other meat curries."))

recipes.append(make(232,"Jackfruit Seed Curry","curry","easy",15,30,4,"Sabaragamuwa",1,[("jackfruit seeds","300g"),("onion","1"),("curry powder","1 tbsp"),("chili powder","1/2 tsp"),("turmeric","1/4 tsp"),("coconut milk","200ml"),("curry leaves","1 sprig"),("Maldive fish","1 tbsp"),("mustard seeds","1/2 tsp")],"1. Boil jackfruit seeds until tender, peel off outer skin\n2. Cut seeds in half\n3. Heat oil, add mustard seeds\n4. Saute onions and curry leaves\n5. Add seeds, spices, Maldive fish, coconut milk\n6. Simmer 20 minutes","Boil seeds until you can easily peel the outer brown skin.","In Sri Lanka, nothing from the jackfruit is wasted - the fruit, seeds, and even the young leaves are all used. This zero-waste approach reflects traditional sustainability."))

recipes.append(make(233,"Liver Curry","curry","medium",15,30,4,"Island-wide",3,[("chicken liver","400g"),("onion","2"),("tomato","1"),("curry powder","2 tbsp"),("chili powder","1 tsp"),("turmeric","1/2 tsp"),("coconut milk","150ml"),("curry leaves","1 sprig"),("garlic","4 cloves"),("ginger","1 inch"),("vinegar","1 tsp")],"1. Clean liver, cut into bite-sized pieces\n2. Heat oil, saute onions, garlic, ginger\n3. Add tomato, curry powder, chili, turmeric\n4. Add liver, stir-fry 5 minutes on high heat\n5. Add coconut milk, vinegar, curry leaves\n6. Simmer 15 minutes - do not overcook","A splash of vinegar removes the metallic taste from liver.","Liver curry is a nutritious and affordable dish prized for its high iron content. It is commonly available as a side dish in Sri Lankan rice and curry restaurants."))

recipes.append(make(234,"Wild Boar Curry (Wal Ura Curry)","curry","hard",30,120,6,"Sabaragamuwa",4,[("wild boar meat","1 kg"),("onion","3"),("curry powder","4 tbsp"),("chili powder","2 tsp"),("turmeric","1 tsp"),("coconut milk","500ml"),("vinegar","3 tbsp"),("garlic","10 cloves"),("ginger","2 inch"),("cinnamon stick","2"),("cardamom","5 pods"),("black pepper","1 tbsp"),("curry leaves","3 sprigs"),("goraka","4 pieces")],"1. Cut meat into cubes, marinate with vinegar, garlic, ginger, spices overnight\n2. Heat oil, add whole spices\n3. Brown onions until dark\n4. Add marinated meat, sear 10 minutes\n5. Add coconut milk, goraka, curry leaves, cover and cook 2 hours\n6. Reduce sauce until thick and rich","Long, slow cooking is essential for this tough meat.","Wild boar curry is an ancient Lankan recipe still prepared in rural areas of Sabaragamuwa and Uva. Its intense, gamey flavor is highly prized by meat lovers."))

recipes.append(make(235,"Chickpea Curry (Kadala Curry)","curry","easy",15,35,4,"Northern Province",2,[("chickpeas","2 cups"),("onion","2"),("tomato","1"),("curry powder","2 tbsp"),("chili powder","1 tsp"),("turmeric","1/2 tsp"),("coconut milk","300ml"),("curry leaves","1 sprig"),("garlic","4 cloves"),("ginger","1 inch"),("mustard seeds","1/2 tsp"),("cumin seeds","1/4 tsp")],"1. Soak chickpeas overnight, boil until tender\n2. Heat oil, add mustard and cumin seeds\n3. Saute onions, garlic, ginger until golden\n4. Add tomato, all spices, cook 5 minutes\n5. Add boiled chickpeas, thin coconut milk\n6. Simmer 20 minutes, add thick coconut milk last","Soaking overnight with a pinch of baking soda makes chickpeas cook faster.","Kadala curry is a protein-rich vegetarian curry beloved in Northern Province. It is especially popular as an accompaniment to pittu and hoppers."))

# Save part 1
with open("generate_recipes_data_p1.json","w",encoding="utf-8") as f:
    json.dump(recipes, f, indent=2, ensure_ascii=False)
print(f"Part 1: {len(recipes)} curry recipes (SL_0191-SL_0235) saved")
